### ISSUE TITLE
Variable loading failed

### ISSUE THREAD

**Issue by 157946a** [Andre601/Formatter-Expansion#3]
The error is:

[23:58:50 ERROR]: [PlaceholderAPI] failed to load class files of expansions
java.util.concurrent.CompletionException: java.lang.UnsupportedClassVersionError: com/andre601/formatterexpansion/FormatterExpansion$1 has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_131]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_131]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) ~[?:1.8.0_131]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[?:1.8.0_131]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_131]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_131]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_131]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_131]
Caused by: java.lang.UnsupportedClassVersionError: com/andre601/formatterexpansion/FormatterExpansion$1 has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up 
to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_131]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_131]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_131]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_131]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_131]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_131]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_131]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        at me.clip.placeholderapi.util.FileUtil.findClass(FileUtil.java:63) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$4(LocalExpansionManager.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_131]
        ... 5 more

I don't know what the reason is, the error is reported after papi reload, the environment is java8, the core paper-1.12.2

**Comment by Andre601** [comment]
Update Java.

**Comment by 157946a** [comment]
Can't you add one to support java8
